# Generated by Django 6.0.7 on 2026-07-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial_core_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=1000)),
                ('reference_type', models.CharField(choices=[('url', 'URL'), ('filesystem', 'Filesystem')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('lens', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.CharField(blank=True, max_length=255, null=True)),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.resourceregistry')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='PhotoArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.photo')),
            ],
            options={
                'db_table': 'photo_artist',
                'unique_together': {('photo', 'artist')},
            },
        ),
    ]
